/**
 * Fila de triagem — implementação fiel à skill `engineering/triage`
 * (github.com/mattpocock/skills): máquina de estados com EXATAMENTE
 * 1 categoria + 1 estado por item.
 *
 *   Categorias: bug | enhancement
 *   Estados:    needs-triage | needs-info | ready-for-agent | ready-for-human | wontfix
 *   Transições: unlabeled → needs-triage → (needs-info ⇄ needs-triage) →
 *               ready-for-agent | ready-for-human | wontfix
 *
 * Vive em `.tic-code/triage.json` (sobrevive entre análises, como snapshots).
 * Itens são gerados automaticamente pela pipeline (riscos critical/high e
 * violações de regra `error`) e manualmente pela UI/MCP.
 */
import * as fs from 'fs';
import * as path from 'path';

export const TRIAGE_FILE = 'triage.json';
export const TRIAGE_DISCLAIMER = '*This was generated by AI during triage.*';

export type TriageCategory = 'bug' | 'enhancement';
export type TriageState = 'needs-triage' | 'needs-info' | 'ready-for-agent' | 'ready-for-human' | 'wontfix' | 'done';
export type TriagePriority = 'critical' | 'high' | 'medium' | 'low';
export type TriageSource = 'risk' | 'arch-rule' | 'pr-gate' | 'manual';

export interface TriageItem {
  id: string;
  title: string;
  category: TriageCategory;
  state: TriageState;
  priority: TriagePriority;
  source: TriageSource;
  /** Entidade do grafo associada (file:..., plsql:..., etc.) ou arquivo. */
  entity?: string;
  detail?: string;
  createdAt: string;
  updatedAt: string;
  history: Array<{ state: TriageState; at: string }>;
}

const VALID_TRANSITIONS: Record<TriageState, TriageState[]> = {
  'needs-triage': ['needs-info', 'ready-for-agent', 'ready-for-human', 'wontfix'],
  'needs-info': ['needs-triage'],
  'ready-for-agent': ['needs-triage', 'done'],
  'ready-for-human': ['needs-triage', 'done'],
  'wontfix': ['needs-triage'],
  'done': []
};

export function loadTriage(ticCodeDir: string): TriageItem[] {
  const file = path.join(ticCodeDir, TRIAGE_FILE);
  if (!fs.existsSync(file)) return [];
  try {
    const parsed = JSON.parse(fs.readFileSync(file, 'utf8'));
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function saveTriage(ticCodeDir: string, items: TriageItem[]): void {
  fs.writeFileSync(path.join(ticCodeDir, TRIAGE_FILE), JSON.stringify(items, null, 2), 'utf8');
}

export interface TriageCandidate {
  /** Id determinístico (dedup entre análises): ex. `risk::file::titulo` */
  id: string;
  title: string;
  category: TriageCategory;
  priority: TriagePriority;
  source: TriageSource;
  entity?: string;
  detail?: string;
}

/**
 * Sincroniza candidatos detectados pela análise com a fila existente:
 * novos entram como `needs-triage`; existentes PRESERVAM estado/histórico
 * (a skill exige que a triagem humana não seja sobrescrita pela máquina).
 */
export function syncTriageItems(ticCodeDir: string, candidates: TriageCandidate[]): { created: number; total: number } {
  const items = loadTriage(ticCodeDir);
  const byId = new Map(items.map((i) => [i.id, i]));
  const now = new Date().toISOString();
  let created = 0;
  for (const c of candidates) {
    if (byId.has(c.id)) continue;
    created++;
    items.push({
      ...c,
      state: 'needs-triage',
      createdAt: now,
      updatedAt: now,
      history: [{ state: 'needs-triage', at: now }]
    });
  }
  saveTriage(ticCodeDir, items);
  return { created, total: items.length };
}

export function createManualItem(
  ticCodeDir: string,
  input: { title: string; category: TriageCategory; priority?: TriagePriority; entity?: string; detail?: string }
): TriageItem {
  const items = loadTriage(ticCodeDir);
  const now = new Date().toISOString();
  const item: TriageItem = {
    id: `manual::${Date.now().toString(36)}`,
    title: input.title,
    category: input.category,
    state: 'needs-triage',
    priority: input.priority ?? 'medium',
    source: 'manual',
    entity: input.entity,
    detail: input.detail,
    createdAt: now,
    updatedAt: now,
    history: [{ state: 'needs-triage', at: now }]
  };
  items.push(item);
  saveTriage(ticCodeDir, items);
  return item;
}

export function transitionTriageItem(
  ticCodeDir: string,
  id: string,
  changes: { state?: TriageState; category?: TriageCategory; priority?: TriagePriority }
): { ok: boolean; error?: string; item?: TriageItem } {
  const items = loadTriage(ticCodeDir);
  const item = items.find((i) => i.id === id);
  if (!item) return { ok: false, error: `Item "${id}" não encontrado.` };

  if (changes.state && changes.state !== item.state) {
    const allowed = VALID_TRANSITIONS[item.state] ?? [];
    if (!allowed.includes(changes.state)) {
      return { ok: false, error: `Transição inválida: ${item.state} → ${changes.state}. Permitidas: ${allowed.join(', ') || '(nenhuma)'}` };
    }
    item.state = changes.state;
    item.history.push({ state: changes.state, at: new Date().toISOString() });
  }
  if (changes.category) item.category = changes.category;
  if (changes.priority) item.priority = changes.priority;
  item.updatedAt = new Date().toISOString();
  saveTriage(ticCodeDir, items);
  return { ok: true, item };
}
