export type Confidence = 'CONFIRMED' | 'INFERRED' | 'GAP';

export interface ScreenHints { screenName?: string; visibleTerms?: string[]; mainAction?: string; targetElement?: string; targetField?: string; targetRule?: string; }
export interface ScreenImpactInput { id: string; url?: string; normalizedRoute?: string; screenshotPath?: string; screenshotFileName?: string; changeDescription: string; userHints: ScreenHints; createdAt: string; }
export interface ScreenFingerprint { id: string; screenshotPath?: string; screenshotFileName?: string; screenshotMetadata: { extension?: string; sizeBytes?: number; width?: number; height?: number; }; url?: string; normalizedRoute?: string; changeDescription: string; userHints: ScreenHints; imageMode: 'local-reference'; visionEnabled: false; candidateKeywords: string[]; candidateRoutes: string[]; candidateComponents: string[]; candidateApiCalls: string[]; createdAt: string; }
export interface FrontendScreenMatch { route?: string; file: string; componentName?: string; projectId?: string; matchScore: number; matchedSignals: string[]; confidence: Confidence; evidence: string[]; matchedBy: Array<'exact-route'|'route-pattern'|'filename'|'component-name'|'visible-term'|'i18n'|'label'|'inferred'>; }
export interface ApiCallMatch { method?: string; path: string; file: string; line?: number; caller?: string; confidence: Confidence; evidence: string[]; }
export interface BackendEndpointMatch { method?: string; path: string; controllerFile: string; controllerClass?: string; controllerMethod?: string; serviceCandidates: string[]; confidence: Confidence; evidence: string[]; }
export interface BackendFlowNode { type: 'controller'|'service'|'bo'|'repository'|'dao'|'sql-resource'|'config'|'unknown'; file: string; symbol?: string; confidence: Confidence; evidence: string[]; }
export interface DatabaseImpact { sqlFiles: string[]; tables: string[]; views: string[]; functions: string[]; procedures: string[]; packages: string[]; triggers: string[]; readOperations: string[]; writeOperations: string[]; confidence: Confidence; evidence: string[]; }
export interface FileEditCandidate { file: string; category: 'edit'|'review-before-edit'|'possibly-impacted'|'test'; stack: 'frontend'|'backend'|'database'|'test'|'config'|'unknown'; reason: string; confidence: Confidence; changeType: 'style'|'component'|'route'|'api-client'|'endpoint'|'service'|'repository'|'sql'|'plsql'|'permission'|'validation'|'test'|'config'; priority: 1|2|3|4|5; evidence: string[]; }
export interface ImpactEstimate { level: 'LOW'|'MEDIUM'|'HIGH'|'CRITICAL'; score: number; reasons: string[]; risks: string[]; recommendedFilesToReview: string[]; recommendedQuestions: string[]; estimatedEffort: { minHours: number; maxHours: number; label: string; assumptions: string[]; }; }
export interface AiChangePackage { screenSummary: string; requestedChange: string; impactSummary: string; filesToEdit: FileEditCandidate[]; filesToReview: FileEditCandidate[]; backendTrace: BackendFlowNode[]; databaseTrace: DatabaseImpact; risks: string[]; gaps: string[]; questions: string[]; safeImplementationPrompt: string; tokenBudgetHint: string; createdAt: string; }
export interface ScreenImpactResult { input: ScreenImpactInput; fingerprint: ScreenFingerprint; frontendMatches: FrontendScreenMatch[]; apiCalls: ApiCallMatch[]; backendEndpoints: BackendEndpointMatch[]; backendFlow: BackendFlowNode[]; databaseImpact: DatabaseImpact; fileCandidates: FileEditCandidate[]; impactEstimate: ImpactEstimate; gaps: string[]; questions: string[]; generatedFiles: string[]; }
